version: '3.9'
services:
  db:
    image: postgres
    container_name: Postgres_db
    volumes:
      - ./data/db:/var/lib/db/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cash:
    image: redis
    container_name: Redis_Cashdb
    volumes:
      - ./data/db/cash:/data
  
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=django-insecure-)38w+4_z%!vfuf6pky!@vs*dnz@u3=wjww&%nb8p4147r__&#x
      - DEBUG=True
    depends_on:
      - db